export interface Episode {
  id: string;
  episodeNumber: number;
  title: string;
  duration: string;
  durationMin: number;
  isFree: boolean;
  thumbnailEmoji: string;
  thumbnailUrl?: string;
  description: string;
  publishDate: string;
  rating: string;
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  videoId: string;
  tags: string[];
}

export interface Season {
  id: string;
  seasonNumber: number;
  title: string;
  subtitle: string;
  tagline: string;
  badge: string;
  status: "LIVE NOW" | "COMING SOON";
  posterUrl: string;
  tags: string[];
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  category: "HARDWARE" | "SOFTWARE" | "BOTH";
  description: string;
  episodesCount: number;
  episodes: Episode[];
  progressPercent?: number; // resume watching progress
}

export const SEASONS_DATA: Season[] = [
  {
    id: "s1",
    seasonNumber: 1,
    title: "ORIGIN",
    subtitle: "Season 1 · 7 episodes",
    tagline: "The System Wakes",
    badge: "S1 · ORIGIN",
    status: "LIVE NOW",
    posterUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S1%20%281%29-avz4ahw0hI3JddejJeXYP8Ed4bKc9K.png",
    tags: ["Arduino", "ESP32", "C++", "Linux", "Electronics"],
    difficulty: "BEGINNER",
    category: "BOTH",
    description: "Your absolute beginning in robotics. Learn the fundamental principles of electricity, setup your first microcontroller brain, write C++ code to read real sensors, and master the command line like an embedded systems engineer.",
    episodesCount: 7,
    progressPercent: 78,
    episodes: [
      {
        id: "s1e1",
        episodeNumber: 1,
        title: "Electricity Unlocked",
        duration: "22 min",
        durationMin: 22,
        isFree: true,
        thumbnailEmoji: "⚡",
        description: "Demystify voltage, current, resistance, and Ohm's Law. Build your first hardware circuits on a breadboard and learn how to measure power constraints without frying your microcontrollers.",
        publishDate: "Oct 2025",
        rating: "4.9/5",
        difficulty: "BEGINNER",
        videoId: "electricity-unlocked-101",
        tags: ["Circuits", "Multimeter", "Ohm's Law"]
      },
      {
        id: "s1e2",
        episodeNumber: 2,
        title: "Your First Brain",
        duration: "35 min",
        durationMin: 35,
        isFree: false,
        thumbnailEmoji: "🧠",
        description: "Introduction to Arduino and ESP32 architectures. Learn to install the IDE, configure drivers, flash firmware, and control your first GPIO outputs to control LED matrices.",
        publishDate: "Oct 2025",
        rating: "4.8/5",
        difficulty: "BEGINNER",
        videoId: "your-first-brain-102",
        tags: ["Arduino", "ESP32", "IDE Setup"]
      },
      {
        id: "s1e3",
        episodeNumber: 3,
        title: "Making It Move",
        duration: "28 min",
        durationMin: 28,
        isFree: false,
        thumbnailEmoji: "⚙️",
        description: "DC motors, servo motors, and motor drivers. Understand how PWM control works, how H-bridges work, and write logic to rotate actuators to precise angular coordinates.",
        publishDate: "Oct 2025",
        rating: "4.9/5",
        difficulty: "BEGINNER",
        videoId: "making-it-move-103",
        tags: ["Motors", "Servos", "PWM", "L298N"]
      },
      {
        id: "s1e4",
        episodeNumber: 4,
        title: "Teaching It to Feel",
        duration: "31 min",
        durationMin: 31,
        isFree: false,
        thumbnailEmoji: "📡",
        description: "Interface ultrasonic distance sensors, infrared obstacle detectors, and light dependent resistors. Build your first reactive obstacle avoidance algorithm.",
        publishDate: "Nov 2025",
        rating: "4.7/5",
        difficulty: "BEGINNER",
        videoId: "teaching-it-to-feel-104",
        tags: ["Sensors", "Ultrasonic", "IR Sensors"]
      },
      {
        id: "s1e5",
        episodeNumber: 5,
        title: "C++ That Does Things",
        duration: "40 min",
        durationMin: 40,
        isFree: false,
        thumbnailEmoji: "💻",
        description: "Dive deep into hardware-oriented C++. Master registers, interrupts, functions, logical operators, conditional loops, and memory optimization for low-level embedded hardware.",
        publishDate: "Nov 2025",
        rating: "4.9/5",
        difficulty: "BEGINNER",
        videoId: "cpp-that-does-things-105",
        tags: ["C++", "Interrupts", "Memory", "Logic"]
      },
      {
        id: "s1e6",
        episodeNumber: 6,
        title: "Python Meets the Machine",
        duration: "38 min",
        durationMin: 38,
        isFree: false,
        thumbnailEmoji: "🐍",
        description: "Establish robust serial communication between a Raspberry Pi and your microcontroller. Write Python scripts to send commands and parse real-time sensor streams.",
        publishDate: "Dec 2025",
        rating: "4.8/5",
        difficulty: "BEGINNER",
        videoId: "python-meets-machine-106",
        tags: ["Python", "Serial", "Raspberry Pi", "PySerial"]
      },
      {
        id: "s1e7",
        episodeNumber: 7,
        title: "Linux Is Your Workshop",
        duration: "45 min",
        durationMin: 45,
        isFree: false,
        thumbnailEmoji: "🐧",
        description: "Master the Linux command line. Set up headless SSH on your robot controller, script workflows in Bash, run background processes, and configure automated cron startup scripts.",
        publishDate: "Dec 2025",
        rating: "4.9/5",
        difficulty: "BEGINNER",
        videoId: "linux-workshop-107",
        tags: ["Linux", "Terminal", "Bash", "SSH", "Cron"]
      }
    ]
  },
  {
    id: "s2",
    seasonNumber: 2,
    title: "CONTROL",
    subtitle: "Season 2 · 10 episodes",
    tagline: "The Art of Precision",
    badge: "S2 · CONTROL",
    status: "LIVE NOW",
    // We use a beautiful robotic system board image for CONTROL
    posterUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S1%20%281%29-avz4ahw0hI3JddejJeXYP8Ed4bKc9K.png",
    tags: ["ROS2", "PID", "Sensor Fusion", "IMU", "Filters"],
    difficulty: "INTERMEDIATE",
    category: "SOFTWARE",
    description: "Take command of robotic motion. Learn ROS2 (Robot Operating System), build PID speed & position control loops from scratch, and fuse accelerometer & gyroscope data to calculate exact 3D orientation.",
    episodesCount: 10,
    progressPercent: 42,
    episodes: [
      {
        id: "s2e1",
        episodeNumber: 1,
        title: "ROS2 First Steps",
        duration: "42 min",
        durationMin: 42,
        isFree: true,
        thumbnailEmoji: "🤖",
        description: "Understand the industry-standard framework. Learn ROS2 workspaces, nodes, topics, publishers, and subscribers to build modular software components.",
        publishDate: "Jan 2026",
        rating: "4.9/5",
        difficulty: "INTERMEDIATE",
        videoId: "ros2-first-steps-201",
        tags: ["ROS2", "Nodes", "PubSub", "Linux"]
      },
      {
        id: "s2e2",
        episodeNumber: 2,
        title: "PID Explained",
        duration: "36 min",
        durationMin: 36,
        isFree: false,
        thumbnailEmoji: "📈",
        description: "Master proportional, integral, and derivative control loops. Write code to eliminate overshoot and steer actuators with mathematical precision.",
        publishDate: "Jan 2026",
        rating: "4.8/5",
        difficulty: "INTERMEDIATE",
        videoId: "pid-explained-202",
        tags: ["PID Control", "Actuators", "Mathematics"]
      },
      {
        id: "s2e3",
        episodeNumber: 3,
        title: "Sensor Fusion Basics",
        duration: "44 min",
        durationMin: 44,
        isFree: false,
        thumbnailEmoji: "🔮",
        description: "Why single sensors lie. Combine encoder counts and IMU data to estimate your robot's pose with high-frequency accuracy using complementary filters.",
        publishDate: "Feb 2026",
        rating: "4.9/5",
        difficulty: "INTERMEDIATE",
        videoId: "sensor-fusion-203",
        tags: ["Sensor Fusion", "IMU", "Pose Estimation"]
      },
      {
        id: "s2e4",
        episodeNumber: 4,
        title: "Kalman Filters Demystified",
        duration: "38 min",
        durationMin: 38,
        isFree: false,
        thumbnailEmoji: "📉",
        description: "Implement a 1D Kalman Filter in C++ to eliminate measurement noise from noisy ultrasonic and laser sensors in real-time.",
        publishDate: "Feb 2026",
        rating: "4.8/5",
        difficulty: "INTERMEDIATE",
        videoId: "kalman-filters-204",
        tags: ["Kalman Filter", "Math", "Filtering", "Noise"]
      },
      {
        id: "s2e5",
        episodeNumber: 5,
        title: "Encoder Odometry",
        duration: "40 min",
        durationMin: 40,
        isFree: false,
        thumbnailEmoji: "🎡",
        description: "Decode quadrature encoders to track wheel rotation, calculating distance traveled, linear velocity, and angular trajectory.",
        publishDate: "Mar 2026",
        rating: "4.7/5",
        difficulty: "INTERMEDIATE",
        videoId: "encoder-odometry-205",
        tags: ["Quadrature", "Encoders", "Odometry"]
      },
      {
        id: "s2e6",
        episodeNumber: 6,
        title: "IMU Calibration",
        duration: "35 min",
        durationMin: 35,
        isFree: false,
        thumbnailEmoji: "🧭",
        description: "Eliminate gyroscope drift and accelerometer offsets. Write calibration routines to store calibration matrices in the microchip's EEPROM.",
        publishDate: "Mar 2026",
        rating: "4.8/5",
        difficulty: "INTERMEDIATE",
        videoId: "imu-calibration-206",
        tags: ["IMU", "EEPROM", "Drift Calibration"]
      },
      {
        id: "s2e7",
        episodeNumber: 7,
        title: "Control Loops",
        duration: "32 min",
        durationMin: 32,
        isFree: false,
        thumbnailEmoji: "🔄",
        description: "Develop high-speed execution loops using hardware timer interrupts to ensure deterministic frequency execution of control logic.",
        publishDate: "Apr 2026",
        rating: "4.9/5",
        difficulty: "INTERMEDIATE",
        videoId: "control-loops-207",
        tags: ["Timers", "Interrupts", "RTOS"]
      },
      {
        id: "s2e8",
        episodeNumber: 8,
        title: "Tuning PID Coefficients",
        duration: "45 min",
        durationMin: 45,
        isFree: false,
        thumbnailEmoji: "🎛️",
        description: "Learn systematic tuning techniques (Ziegler-Nichols, trial-and-error) in simulated environments and apply them directly to hardware.",
        publishDate: "Apr 2026",
        rating: "4.7/5",
        difficulty: "INTERMEDIATE",
        videoId: "tuning-pid-208",
        tags: ["PID Tuning", "Stability", "Ziegler-Nichols"]
      },
      {
        id: "s2e9",
        episodeNumber: 9,
        title: "Actuator Mechanics",
        duration: "28 min",
        durationMin: 28,
        isFree: false,
        thumbnailEmoji: "🦾",
        description: "Understand gear ratios, torque calculations, and the electrical current spikes generated under heavy physical robotic loads.",
        publishDate: "May 2026",
        rating: "4.6/5",
        difficulty: "INTERMEDIATE",
        videoId: "actuator-mechanics-209",
        tags: ["Motors", "Torque", "Gear Ratios"]
      },
      {
        id: "s2e10",
        episodeNumber: 10,
        title: "Feedback Systems",
        duration: "50 min",
        durationMin: 50,
        isFree: false,
        thumbnailEmoji: "📡",
        description: "Wire an entire closed-loop control system. Combine your nodes, sensor feedback, and motor controllers into a unified self-correcting machine.",
        publishDate: "May 2026",
        rating: "4.9/5",
        difficulty: "INTERMEDIATE",
        videoId: "feedback-systems-210",
        tags: ["Closed Loop", "Feedback", "System Integration"]
      }
    ]
  },
  {
    id: "s3",
    seasonNumber: 3,
    title: "AUTONOMY",
    subtitle: "Season 3 · 10 episodes",
    tagline: "Vision & Navigation",
    badge: "S3 · AUTONOMY",
    status: "LIVE NOW",
    posterUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/GhostRover-P5s9genDniu6jkV89P8PlPM6mFchoR.jpeg",
    tags: ["OpenCV", "SLAM", "Path Planning", "Computer Vision", "LiDAR"],
    difficulty: "ADVANCED",
    category: "SOFTWARE",
    description: "Give your robot eyes and spatial intelligence. Learn computer vision, write Python code for obstacle avoidance and line following, configure SLAM to map complex rooms, and write intelligent path planning algorithms.",
    episodesCount: 10,
    progressPercent: 0,
    episodes: [
      {
        id: "s3e1",
        episodeNumber: 1,
        title: "Computer Vision Intro",
        duration: "48 min",
        durationMin: 48,
        isFree: true,
        thumbnailEmoji: "👁️",
        description: "Dive into image arrays, color thresholds, and pixel filters. Configure OpenCV on a Raspberry Pi to isolate targets and detect movement from a USB camera feed.",
        publishDate: "Jun 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "computer-vision-intro-301",
        tags: ["OpenCV", "Python", "Image Processing"]
      },
      {
        id: "s3e2",
        episodeNumber: 2,
        title: "SLAM Fundamentals",
        duration: "52 min",
        durationMin: 52,
        isFree: false,
        thumbnailEmoji: "🗺️",
        description: "Simultaneous Localization and Mapping. Discover how a robot can dynamically map an unknown room while tracking its own coordinates inside it.",
        publishDate: "Jun 2026",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "slam-fundamentals-302",
        tags: ["SLAM", "Mapping", "Gmapping"]
      },
      {
        id: "s3e3",
        episodeNumber: 3,
        title: "Path Planning",
        duration: "46 min",
        durationMin: 46,
        isFree: false,
        thumbnailEmoji: "📍",
        description: "Plot trajectories through cluttered spaces. Write A* and Dijkstra search algorithms in Python to find the shortest collision-free routes.",
        publishDate: "Jul 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "path-planning-303",
        tags: ["Algorithms", "Path Planning", "A*", "Dijkstra"]
      },
      {
        id: "s3e4",
        episodeNumber: 4,
        title: "Object Tracking",
        duration: "40 min",
        durationMin: 40,
        isFree: false,
        thumbnailEmoji: "🎯",
        description: "Implement color space masking (HSV) and bounding box contours to detect and track specific objects in three-dimensional space.",
        publishDate: "Jul 2026",
        rating: "4.7/5",
        difficulty: "ADVANCED",
        videoId: "object-tracking-304",
        tags: ["Contours", "HSV Masking", "Target Tracking"]
      },
      {
        id: "s3e5",
        episodeNumber: 5,
        title: "LiDAR Scanning",
        duration: "50 min",
        durationMin: 50,
        isFree: false,
        thumbnailEmoji: "📡",
        description: "Interface a 360-degree laser range scanner. Parse range polar coordinates to locate surrounding wall profiles.",
        publishDate: "Aug 2026",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "lidar-scanning-305",
        tags: ["LiDAR", "Laser Scan", "Point Cloud"]
      },
      {
        id: "s3e6",
        episodeNumber: 6,
        title: "Localization & Mapping",
        duration: "42 min",
        durationMin: 42,
        isFree: false,
        thumbnailEmoji: "🗺️",
        description: "Configure AMCL (Adaptive Monte Carlo Localization) to localize the robot within a pre-built reference occupancy grid map.",
        publishDate: "Aug 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "localization-mapping-306",
        tags: ["AMCL", "Monte Carlo", "Localization"]
      },
      {
        id: "s3e7",
        episodeNumber: 7,
        title: "A* Search Algorithm",
        duration: "38 min",
        durationMin: 38,
        isFree: false,
        thumbnailEmoji: "🌟",
        description: "Optimize grid-based obstacle maps and program a pathfinding routine that avoids obstacles dynamically as they are detected.",
        publishDate: "Sep 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "astar-algorithm-307",
        tags: ["A* Search", "Heuristics", "Pathfinding"]
      },
      {
        id: "s3e8",
        episodeNumber: 8,
        title: "Obstacle Avoidance",
        duration: "44 min",
        durationMin: 44,
        isFree: false,
        thumbnailEmoji: "🛡️",
        description: "Program Dynamic Window Approach (DWA) navigation in ROS2 to steer around moving obstacles at optimal safe velocities.",
        publishDate: "Sep 2026",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "obstacle-avoidance-308",
        tags: ["DWA", "Local Planner", "Collision Avoidance"]
      },
      {
        id: "s3e9",
        episodeNumber: 9,
        title: "Deep Learning for Navigation",
        duration: "55 min",
        durationMin: 55,
        isFree: false,
        thumbnailEmoji: "🧠",
        description: "Introduction to neural network architectures. Train a lightweight convolutional neural network to drive a simulated rover autonomously.",
        publishDate: "Oct 2026",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "deep-learning-nav-309",
        tags: ["PyTorch", "CNN", "Machine Learning"]
      },
      {
        id: "s3e10",
        episodeNumber: 10,
        title: "Fully Autonomous Run",
        duration: "60 min",
        durationMin: 60,
        isFree: false,
        thumbnailEmoji: "🏁",
        description: "The graduation run. Load map parameters, activate SLAM, trigger path planning, and watch your rover navigate from point A to B safely.",
        publishDate: "Oct 2026",
        rating: "5.0/5",
        difficulty: "ADVANCED",
        videoId: "autonomous-run-310",
        tags: ["Autonomous Run", "System Validation", "Deployment"]
      }
    ]
  },
  {
    id: "s4",
    seasonNumber: 4,
    title: "EVOLUTION",
    subtitle: "Season 4 · 12 episodes",
    tagline: "Robotic Arm Mechanics",
    badge: "S4 · EVOLUTION",
    status: "COMING SOON",
    posterUrl: "https://roboflix.xair.live/ironarm.png",
    tags: ["Kinematics", "MoveIt", "CAD", "Servos", "ESP32"],
    difficulty: "ADVANCED",
    category: "HARDWARE",
    description: "Design and build a multi-axis physical robotic manipulator. Calculate Forward and Inverse Kinematics to guide the tip in three-dimensional Cartesian coordinates.",
    episodesCount: 12,
    progressPercent: 0,
    episodes: [
      {
        id: "s4e1",
        episodeNumber: 1,
        title: "Robotic Arm Mechanics",
        duration: "38 min",
        durationMin: 38,
        isFree: true,
        thumbnailEmoji: "🦾",
        description: "Learn about degrees of freedom, joint limits, torque requirements, structural brackets, and end effector mechanisms.",
        publishDate: "Nov 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "robotic-arm-mechanics-401",
        tags: ["Mechanics", "Torque", "Degrees of Freedom"]
      },
      {
        id: "s4e2",
        episodeNumber: 2,
        title: "Inverse Kinematics",
        duration: "55 min",
        durationMin: 55,
        isFree: false,
        thumbnailEmoji: "📐",
        description: "The core math. Convert desired end-effector X, Y, Z space target coordinates into precise rotation angles for individual joint servos.",
        publishDate: "Nov 2026",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "inverse-kinematics-402",
        tags: ["Inverse Kinematics", "Math", "Trigonometry"]
      },
      {
        id: "s4e3",
        episodeNumber: 3,
        title: "Forward Kinematics",
        duration: "42 min",
        durationMin: 42,
        isFree: false,
        thumbnailEmoji: "📏",
        description: "Compute the end effector's absolute coordinate based on the feedback angles of the joint servos using matrix multiplications.",
        publishDate: "Dec 2026",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "forward-kinematics-403",
        tags: ["Forward Kinematics", "Matrix Math"]
      },
      {
        id: "s4e4",
        episodeNumber: 4,
        title: "Joint Coordinates",
        duration: "35 min",
        durationMin: 35,
        isFree: false,
        thumbnailEmoji: "🌐",
        description: "Program reference coordinate frames and build joint limit safety nets to prevent robotic joints from colliding with their own framework.",
        publishDate: "Dec 2026",
        rating: "4.7/5",
        difficulty: "ADVANCED",
        videoId: "joint-coordinates-404",
        tags: ["Joint Limits", "Safety", "Embedded Code"]
      },
      {
        id: "s4e5",
        episodeNumber: 5,
        title: "Gripper Systems",
        duration: "30 min",
        durationMin: 30,
        isFree: false,
        thumbnailEmoji: "✊",
        description: "Design custom end-effectors, calculate dynamic grip torque limits, and write servo control logic to grab fragile and solid items.",
        publishDate: "Jan 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "gripper-systems-405",
        tags: ["Grippers", "Mechanical Design", "Payload Calculations"]
      },
      {
        id: "s4e6",
        episodeNumber: 6,
        title: "DH Parameters",
        duration: "48 min",
        durationMin: 48,
        isFree: false,
        thumbnailEmoji: "📐",
        description: "Construct joint reference chains using Denavit-Hartenberg parameters to model complex robotic manipulators mathematically.",
        publishDate: "Jan 2027",
        rating: "4.7/5",
        difficulty: "ADVANCED",
        videoId: "dh-parameters-406",
        tags: ["DH Parameters", "Transformations", "Linear Algebra"]
      },
      {
        id: "s4e7",
        episodeNumber: 7,
        title: "Trajectory Generation",
        duration: "40 min",
        durationMin: 40,
        isFree: false,
        thumbnailEmoji: "📈",
        description: "Program smooth S-curve profiles to accelerate and decelerate joints smoothly, avoiding sudden mechanical torque vibrations.",
        publishDate: "Feb 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "trajectory-generation-407",
        tags: ["S-Curve", "Acceleration", "Smoothing"]
      },
      {
        id: "s4e8",
        episodeNumber: 8,
        title: "Torque Calculation",
        duration: "45 min",
        durationMin: 45,
        isFree: false,
        thumbnailEmoji: "🏋️",
        description: "Analyze static forces on joint linkages. Determine holding torque required when the arm is fully extended with maximum load.",
        publishDate: "Feb 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "torque-calculation-408",
        tags: ["Torque Analysis", "Statics", "Linkages"]
      },
      {
        id: "s4e9",
        episodeNumber: 9,
        title: "Cartesian Control",
        duration: "50 min",
        durationMin: 50,
        isFree: false,
        thumbnailEmoji: "🧭",
        description: "Implement continuous straight line Cartesian paths, interpolating coordinates between workspace locations incrementally.",
        publishDate: "Mar 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "cartesian-control-409",
        tags: ["Cartesian Interpolation", "Linear Motion"]
      },
      {
        id: "s4e10",
        episodeNumber: 10,
        title: "ESP32 Servo Server",
        duration: "37 min",
        durationMin: 37,
        isFree: false,
        thumbnailEmoji: "🕸️",
        description: "Establish a local web service running on ESP32 to receive control matrices via WebSockets for low-latency wireless control.",
        publishDate: "Mar 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "esp32-servo-server-410",
        tags: ["ESP32", "WebSockets", "Wireless Control"]
      },
      {
        id: "s4e11",
        episodeNumber: 11,
        title: "ROS2 MoveIt Integration",
        duration: "52 min",
        durationMin: 52,
        isFree: false,
        thumbnailEmoji: "🤖",
        description: "Configure MoveIt motion planning stack in ROS2. Setup URDF representation files of your arm and run interactive path planning.",
        publishDate: "Apr 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "ros2-moveit-411",
        tags: ["MoveIt", "URDF", "Path Planning"]
      },
      {
        id: "s4e12",
        episodeNumber: 12,
        title: "Precision Sorting Project",
        duration: "58 min",
        durationMin: 58,
        isFree: false,
        thumbnailEmoji: "🏁",
        description: "The capstone project. Combine computer vision with kinematic picking loops to build a fully automated sorting assembly arm.",
        publishDate: "Apr 2027",
        rating: "5.0/5",
        difficulty: "ADVANCED",
        videoId: "precision-sorting-412",
        tags: ["System Integration", "Sorting Project", "Industrial Demo"]
      }
    ]
  },
  {
    id: "s5",
    seasonNumber: 5,
    title: "DOMINATION",
    subtitle: "Season 5 · 8 episodes",
    tagline: "Hexapod & Gait Generation",
    badge: "S5 · DOMINATION",
    status: "COMING SOON",
    posterUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/FourlegCrab-t98xz8yq1KhLInAVoWEG53ZYazyPsc.jpeg",
    tags: ["Hexapod", "Gait", "Leg Kinematics", "ESP32", "Bluetooth"],
    difficulty: "ADVANCED",
    category: "HARDWARE",
    description: "The ultimate challenge. Design a 6-legged walking hexapod robot. Build multi-joint leg systems, generate tripod walking gaits, and write terrain adaptive sensors controllers.",
    episodesCount: 8,
    progressPercent: 0,
    episodes: [
      {
        id: "s5e1",
        episodeNumber: 1,
        title: "Hexapod Architecture",
        duration: "50 min",
        durationMin: 50,
        isFree: true,
        thumbnailEmoji: "🕷️",
        description: "Understand the mechanical stability, mechanical weight balance, leg distribution, and multi-servo configurations of legged walking robots.",
        publishDate: "May 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "hexapod-architecture-501",
        tags: ["Legged Robots", "Biomimicry", "Mechanics"]
      },
      {
        id: "s5e2",
        episodeNumber: 2,
        title: "Gait Generation",
        duration: "58 min",
        durationMin: 58,
        isFree: false,
        thumbnailEmoji: "🚶",
        description: "Write structural algorithms to generate stable tripod and wave walking gaits, synchronizing phase angles of 18 independent servos.",
        publishDate: "May 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "gait-generation-502",
        tags: ["Gait Generation", "Tripod Gait", "Servo Synchronization"]
      },
      {
        id: "s5e3",
        episodeNumber: 3,
        title: "Tripod Gait Design",
        duration: "45 min",
        durationMin: 45,
        isFree: false,
        thumbnailEmoji: "📐",
        description: "Program dynamic support polygon logic in C++ to keep the center of mass inside the footprint area of three stable ground links.",
        publishDate: "Jun 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "tripod-gait-503",
        tags: ["Support Polygon", "Static Balance"]
      },
      {
        id: "s5e4",
        episodeNumber: 4,
        title: "Leg Kinematics",
        duration: "48 min",
        durationMin: 48,
        isFree: false,
        thumbnailEmoji: "📐",
        description: "Develop 3-DOF kinematic math representations for a single leg structure to place the footpad at arbitrary X, Y, Z locations relative to the main body.",
        publishDate: "Jun 2027",
        rating: "4.7/5",
        difficulty: "ADVANCED",
        videoId: "leg-kinematics-504",
        tags: ["Leg Kinematics", "3-DOF Linkages"]
      },
      {
        id: "s5e5",
        episodeNumber: 5,
        title: "Terrain Adaptation",
        duration: "52 min",
        durationMin: 52,
        isFree: false,
        thumbnailEmoji: "⛰️",
        description: "Interface ground contact switches and distance sensors to adapt walking postures dynamically when walking over rough uneven surfaces.",
        publishDate: "Jul 2027",
        rating: "4.9/5",
        difficulty: "ADVANCED",
        videoId: "terrain-adaptation-505",
        tags: ["Adaptive Walking", "Foot Sensors", "Reactive Control"]
      },
      {
        id: "s5e6",
        episodeNumber: 6,
        title: "ESP32 Leg Controller",
        duration: "40 min",
        durationMin: 40,
        isFree: false,
        thumbnailEmoji: "💾",
        description: "Configure PCA9685 PWM expansion boards on ESP32 to drive all 18 servos concurrently with high precision, optimizing I2C serial speeds.",
        publishDate: "Jul 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "esp32-leg-controller-506",
        tags: ["PCA9685", "I2C Expansion", "ESP32 Firmware"]
      },
      {
        id: "s5e7",
        episodeNumber: 7,
        title: "Bluetooth Remote Control",
        duration: "38 min",
        durationMin: 38,
        isFree: false,
        thumbnailEmoji: "🎮",
        description: "Write raw serial bluetooth parsing profiles to map inputs from a mobile app controller to linear walking vector directions and yaw adjustments.",
        publishDate: "Aug 2027",
        rating: "4.8/5",
        difficulty: "ADVANCED",
        videoId: "bluetooth-remote-507",
        tags: ["Bluetooth", "Controller", "Vector Control"]
      },
      {
        id: "s5e8",
        episodeNumber: 8,
        title: "Full Walking Robot Run",
        duration: "65 min",
        durationMin: 65,
        isFree: false,
        thumbnailEmoji: "🏆",
        description: "Deploy the final hexapod. Observe the mechanical walker balance, rotate, adaptation, and step over real obstacle barriers in this final demo.",
        publishDate: "Aug 2027",
        rating: "5.0/5",
        difficulty: "ADVANCED",
        videoId: "walking-hexapod-demo-508",
        tags: ["System Domination", "Legged Walker Demo", "Graduation Run"]
      }
    ]
  }
];

export const CONTINUE_WATCHING_DATA = [
  {
    episodeId: "s1e3",
    seasonId: "s1",
    seasonTitle: "ORIGIN",
    seasonNumber: 1,
    episodeNumber: 3,
    title: "Making It Move",
    progressPercent: 65,
    durationLeft: "10 mins left",
    duration: "28 min",
    thumbnailUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S1%20%281%29-avz4ahw0hI3JddejJeXYP8Ed4bKc9K.png",
    emoji: "⚙️"
  },
  {
    episodeId: "s2e2",
    seasonId: "s2",
    seasonTitle: "CONTROL",
    seasonNumber: 2,
    episodeNumber: 2,
    title: "PID Explained",
    progressPercent: 20,
    durationLeft: "29 mins left",
    duration: "36 min",
    thumbnailUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/S1%20%281%29-avz4ahw0hI3JddejJeXYP8Ed4bKc9K.png",
    emoji: "📈"
  }
];
